### ISSUE TITLE
ID needs to change to long or string

### ISSUE THREAD

**Issue by IvanJosipovic** [ubisoft/NGitLab#491]
The Job IDs are at "4681067651" in my GitLab.com instance. However, this may impact all IDs.

Running the following code throws an exception:
```
var projects = client.Projects.Get(new ProjectQuery() { });

foreach (var project in projects)
{
    var pipelines = client.GetPipelines(project.Id);

    foreach (var pipeline in pipelines.AllJobs)
    {

    }
}
```

```
System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to System.Int32. Path: $[0].id | LineNumber: 0 | BytePositionInLine: 17.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at NGitLab.Impl.Json.Serializer.Deserialize[T](String json) in /_/NGitLab/Impl/Json/Serializer.cs:line 29
   at NGitLab.Impl.HttpRequestor.Enumerable`1.<GetEnumerator>d__5.MoveNext() in /_/NGitLab/Impl/HttpRequestor.cs:line 193
   at GitLabTool.Worker.<ExecuteAsync>d__4.MoveNext() in C:\Repos\GitLabTool\Worker.cs:line 31
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\Repos\GitLabTool\Program.cs:line 10

Inner Exception 1:
FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
```

**Comment by meziantou** [comment]
That's a major breaking change (source and binary). I'm not sure how we want to handle it.

There are multiple ways:
- Do nothing => It will be ok on most on-premise instances, but will stop supporting gitlab.com. I don't think this is viable for an open-source project...
- Make the change and update the major version => Update nightmare because of the binary breaking change (you may get `MethodNotFoundException` at runtime)
- Use 2 properties `IdInt64` (new) and `Id` (existing)
  - No breaking change
  - Error-prone as you may use the wrong property
  - Adding an `[Obsolete]` attribute would break many projects that auto-update their dependencies and use TreatWarningsAsErrors.

If we go with this breaking change, do we want to make other breaking changes at the same time? (HttpClient / Use Properties everywhere instead of fields / others?)

@jontdelorme @jairbubbles @Toa741 @louis-z What do you think?

**Comment by Toa741** [comment]
I would take the option N°2.

- As you said, doing nothing is not really an option.
- Option 2 might be nightmare mode, it will be more like a short and sharp pain, rather than Option 3 that might take ages for a full migration and to avoid confusions

Tackling other breaking changes that we had in mind since quite a while at the same time could be a good idea too. +1

We should just make sure we don't start refactoring everything and it become a never ending story ^^

**Comment by louis-z** [comment]
I've been dreaming of replacing public fields with properties for a long time now, so I vote for bumping up the major version. 😀 However, if we go that route we should be smart about it and carefully plan for it, i.e. bundle other improvements that we've been holding off because they would break the API.

**Comment by gep13** [comment]
@louis-z has any decision been made about how to proceed with this?

One of the tools that I maintain, GitReleaseManager, is starting to hit this issue when trying to enumerate `ProjectIssueNote` items.

**Comment by gep13** [comment]
@meziantou sorry, meant to tag you in the previous comment as well.

**Comment by louis-z** [comment]
@gep13, unfortunately we still haven't decided yet. We'll try to address it shortly.

BTW, @meziantou is no longer involved in this project.

**Comment by gep13** [comment]
> @louis-z said...
BTW, @meziantou is no longer involved in this project.

Ah, I was not aware of that, thank you for letting me know.

> @louis-z said...
 unfortunately we still haven't decided yet.

Are the options that are being discussed still those that are outlined here:

https://github.com/ubisoft/NGitLab/issues/491#issuecomment-1640906948

Is there any additional discussion happening about this outside this issue that is public?

**Comment by gep13** [comment]
Huge thanks for everyone for getting this fixed!  Really appreciate it!
